#%RAML 1.0 DataType

#This file is the datatype for customer and located at resourceTypes/customer.raml

  properties:
    id:
      type: string
    firstName:
      type: string
    lastName:
        type: string
    updatedTime:
      type: datetime
    streetAddress:
      type: string
    city:
      type: string
    state:
      type: string
    postCode:
      type: string    
