#%RAML 1.0 DataType


  properties:
    id:
      type: string
    firstName:
      type: string
    lastName:
        type: string
    updatedTime:
      type: datetime
    streetAddress:
      type: string
    city:
      type: string
    state:
      type: string
    postCode:
      type: string    
