#%RAML 1.0 DataType

#This file is the datatype for order and located at resourceTypes/order.raml
  properties:
    oid:
      type: string
    item:
      type: string
    quantity:
        type: integer
    total:
      type:  number
    
